import React from "react";
import "./App.css";

function Termo(props) {
  return (
    <div className="termo">
      <p>Termos e Condi&ccedil;&otilde;es</p>
<p>TERMO DE USO DO APLICATIVO BIBI MOTOTAXI PARA PASSAGEIROS</p>
<p>Este Termo de Uso disp&otilde;e as Condi&ccedil;&otilde;es Gerais para os Passageiros, que regem o acesso e uso, como pessoa f&iacute;sica, dentro do Brasil, que se referem ao uso dos servi&ccedil;os prestados atrav&eacute;s de aplica&ccedil;&atilde;o tecnol&oacute;gica BIBI MOTOTAXI, disponibilizados pela BIBI MOTOTAXI, de forma a viabilizar e facilitar a conex&atilde;o entre o Passageiro e o Motorista.</p>
<p>ATEN&Ccedil;&Atilde;O: LEIA ESTE &ldquo;TERMO&rdquo; ANTES DE EFETUAR O CADASTRO NO APLICATIVO BIBI MOTOTAXI. QUALQUER PESSOA F&Iacute;SICA, DORAVANTE DENOMINADA &ldquo;PASSAGEIRO&rdquo;, QUE UTILIZE OS SERVI&Ccedil;OS DO APLICATIVO BIBI MOTOTAXI DECLARA ACEITAR ESTE &ldquo;TERMO&rdquo; E TODAS AS POL&Iacute;TICAS E PRINC&Iacute;PIOS QUE O REGEM.</p>
<p>AO SE CADASTRAR, ACEITAR E UTILIZAR CONTINUAMENTE OS SERVI&Ccedil;OS, O PASSAGEIRO ESTAR&Aacute; DECLARANDO TER LIDO, ENTENDIDO E ACEITO OS &ldquo;TERMOS&rdquo;.</p>
<p>A QUALQUER TEMPO, O PASSAGEIRO N&Atilde;O CONCORDE COM OS TERMOS, DEVER&Aacute; ACESSAR IMEDIATAMENTE A UTILIZA&Ccedil;&Atilde;O DO APLICATIVO E DESINSTAL&Aacute;-LO DE SEU APARELHO.</p>
<p>A ACEITA&Ccedil;&Atilde;O &Eacute; INDISPENS&Aacute;VEL E OBRIGAT&Oacute;RIA PARA A UTILIZA&Ccedil;&Atilde;O DOS SERVI&Ccedil;OS DO APLICATIVO BIBI MOTOTAXI ESTE &ldquo;TERMO&rdquo; CONSTITUI UM DOCUMENTO EXCLUSIVO ENTRE O APLICATIVO BIBI MOTOTAXI E O &ldquo;PASSAGEIRO&rdquo;, SUBSTITUINDO, DESTE MODO, TODOS OS ACORDOS, REPRESENTA&Ccedil;&Otilde;ES, GARANTIAS E ENTENDIMENTOS ANTERIORES COM RELA&Ccedil;&Atilde;O AO APLICATIVO BIBI MOTOTAXI, SEUS CONTE&Uacute;DOS, PRODUTOS OU SERVI&Ccedil;OS FORNECIDOS POR OU POR MEIO DO APLICATIVO.</p>
<p>ATEN&Ccedil;&Atilde;O</p>
<p>ESTE &ldquo;TERMO&rdquo; &Eacute; DESTINADO A REGULAR O USO DO APLICATIVO PELOS &ldquo;PASSAGEIROS&rdquo;, E, DADA SUA PUBLICIDADE, N&Atilde;O &Eacute; PASS&Iacute;VEL DE ALEGA&Ccedil;&Atilde;O DE DESCONHECIMENTO DE SEU CONTE&Uacute;DO POR PARTE DE NENHUM PASSAGEIRO DO APLICATIVO.</p>
<p>OS &ldquo;PASSAGEIROS&rdquo; MENORES DE 18 ANOS SOMENTE PODER&Atilde;O EFETUAR O REGISTRO OU CADASTRO NO &ldquo;APLICATIVO&rdquo; DESDE QUE DEVIDAMENTE REPRESENTADOS OU ASSISTIDOS, CONFORME LEGISLA&Ccedil;&Atilde;O APLIC&Aacute;VEL NO PA&Iacute;S, DEVENDO ESSES SEREM RESPONS&Aacute;VEIS NA ESFERA C&Iacute;VEL POR TODO E QUALQUER ATO PRATICADO PELOS MENORES QUANDO DA UTILIZA&Ccedil;&Atilde;O DESTE &ldquo;APLICATIVO&rdquo;. OS REPRESENTANTES LEGAIS SER&Atilde;O RESPONS&Aacute;VEIS, POR TODO E QUALQUER ATO IL&Iacute;CITO OU CRIMINOSO PRATICADO PELOS MENORES QUANDO DA UTILIZA&Ccedil;&Atilde;O DO &ldquo;APLICATIVO&rdquo;.</p>
<p>DEFINI&Ccedil;&Otilde;ES</p>
<p>APLICATIVO BIBI MOTOTAXI: &eacute; um aplicativo de mobilidade urbana, que permite a conex&atilde;o entre Motorista e Passageiros, possibilitando uma corrida r&aacute;pida e segura. O APLICATIVO BIBI MOTOTAXI viabiliza o contato direto entre o Motorista e o Passageiro atrav&eacute;s da plataforma tecnol&oacute;gica, portanto, os PASSAGEIROS reconhecem que o Aplicativo BIBI MOTOTAXI n&atilde;o possui responsabilidade direta por quaisquer danos causados aos Usu&aacute;rios, os quais reconhecem que o Aplicativo BIBI MOTOTAXI estar&aacute; isento de qualquer dano ao qual n&atilde;o tiver dado causa direta, devendo ser ressarcido diretamente ou indiretamente, de forma regressiva, pelo Passageiro culpado.</p>
<p>PASSAGEIRO: &eacute; aquele usu&aacute;rio que se cadastrou para solicitar servi&ccedil;o de transporte de mobilidade urbana, atrav&eacute;s de Motoristas Aut&ocirc;nomos por meio do Aplicativo BIBI MOTOTAXI. Este passageiro concorda e confirma que o Aplicativo BIBI MOTOTAXI &eacute; uma plataforma que viabiliza e facilita seu contato direto com o Motorista. O Aplicativo BIBI MOTOTAXI se empenhar&aacute; para inexistir eventuais problemas, seja por meio de atendimento a reclama&ccedil;&otilde;es, bloqueios de MOTORISTAS e/ou pesquisas sobre a reputa&ccedil;&atilde;o dos Motorista, por&eacute;m n&atilde;o se responsabiliza por qualquer dano causado que seja de responsabilidade do Motorista, na rela&ccedil;&atilde;o Motorista e Passageiro e/ou decorrente do transporte de pessoas efetuado.</p>
<p>SERVI&Ccedil;OS ADICIONAIS: s&atilde;o os servi&ccedil;os oferecidos pelo Aplicativo BIBI MOTOTAXI al&eacute;m da solicita&ccedil;&atilde;o e atendimento de solicita&ccedil;&otilde;es efetuadas por pessoas f&iacute;sicas, sem distin&ccedil;&atilde;o. Visando atender &agrave;s demandas de seus passageiros, o Aplicativo BIBI MOTOTAXI possui uma gama de servi&ccedil;os oferecidos aos clientes, os quais est&atilde;o relacionados &agrave; principal atividade desenvolvida pelo Aplicativo BIBI MOTOTAXI , possibilitando cada vez mais voc&ecirc; chegar ao seu destino pelo menor custo, com agilidade, praticidade, conforto e econ&ocirc;mica.</p>
<p>Dentre os servi&ccedil;os oferecidos, figuram:</p>
<p>MOTORISTA: &eacute; aquele Usu&aacute;rio que se cadastrou no Aplicativo BIBI MOTOTAXI aceitou os TERMOS de USO de MOTORISTA e as pol&iacute;ticas que o regem, apresentou atrav&eacute;s do Aplicativo todas as documenta&ccedil;&otilde;es solicitadas e foi cadastrado pelo Aplicativo BIBI MOTOTAXI , de acordo com os crit&eacute;rios exigidos para o cadastro.</p>
<p>O Motorista ser&aacute; o &uacute;nico e exclusivo respons&aacute;vel por todos os danos decorrentes dos servi&ccedil;os prestados, de forma que o Aplicativo BIBI MOTOTAXI n&atilde;o poder&aacute; ser responsabilizado por quaisquer danos aos quais n&atilde;o tiver dado causa direta ao Passageiro ou a terceiros.</p>
<p>O Motorista aceitou os termos e condi&ccedil;&otilde;es de uso do Aplicativo BIBI MOTOTAXI. E se obrigou a cumprir todas as regras ao utilizar os servi&ccedil;os do Aplicativo BIBI MOTOTAXI .</p>
<p>DO CADASTRO E DA UTILIZA&Ccedil;&Atilde;O DO SISTEMA</p>
<p>Ao cadastrar-se, o Passageiro concorda que forneceu informa&ccedil;&otilde;es ver&iacute;dicas, completas e atualizadas, conforme solicitado no CADASTRO inicialmente preenchido, n&atilde;o estando o Aplicativo BIBI MOTOTAXI obrigado a fiscalizar ou controlar a veracidade das informa&ccedil;&otilde;es fornecidas. O Passageiro responsabiliza-se, civil e criminalmente, pela veracidade das informa&ccedil;&otilde;es prestadas pelo Aplicativo BIBI MOTOTAXI . Somente as pessoas f&iacute;sicas que tenham plena capacidade legal est&atilde;o autorizadas a se cadastrar no Aplicativo BIBI MOTOTAXI. Pessoas que n&atilde;o possuam essa capacidade, dentre estas os menores de idade, dever&atilde;o estar assistidos por seu representante legal.</p>
<p>O aplicativo BIBI MOTOTAXI se reserva ainda o direito de utilizar todos os meios legais e poss&iacute;veis para identificar seus Passageiros, bem como de solicitar, a qualquer momento, dados adicionais e documentos que considere necess&aacute;rios, a seu exclusivo crit&eacute;rio, com a finalidade de verificar os dados cadastrais informados.</p>
<p>O Aplicativo BIBI MOTOTAXI, n&atilde;o se responsabiliza por qualquer dano que resulte da divulga&ccedil;&atilde;o da senha do Passageiro a terceiros. O Passageiro ser&aacute; o &uacute;nico respons&aacute;vel pela guardada senha de acesso ao Aplicativo BIBI MOTOTAXI. &Eacute; vedada a transfer&ecirc;ncia, cess&atilde;o, comodato ou qualquer tipo de empr&eacute;stimo, por qualquer forma, do cadastro do Passageiro a terceiros. O cadastro do Passageiro &eacute; pessoal e intransfer&iacute;vel.</p>
<p>DA LIMITA&Ccedil;&Atilde;O DE RESPONSABILIDADE ENTRE MOTORISTA E PASSAGEIRO</p>
<p>O Aplicativo BIBI MOTOTAXI &eacute; um intermedi&aacute;rio a fim de otimizar o servi&ccedil;o de transporte privado atrav&eacute;s da plataforma tecnol&oacute;gica. Assim, ao aceitar a presta&ccedil;&atilde;o dos servi&ccedil;os pelo Motorista, o Passageiro reconhece que o Aplicativo BIBI MOTOTAXI n&atilde;o possui v&iacute;nculo direto com o Motorista, apenas facilita o contato entre Motorista e Passageiro.</p>
<p>O Passageiro reconhece e concorda que:</p>
<ol>
<li>a) O Aplicativo BIBI MOTOTAXI n&atilde;o poder&aacute; ser responsabilizado, por quaisquer atos e omiss&otilde;es de quaisquer PASSAGEIROS ou MOTORISTA, seja por assaltos, perdas de compromisso em decorr&ecirc;ncia de qualquer ato, discuss&otilde;es, dentre outros eventos, incluindo o efetivo cumprimento das obriga&ccedil;&otilde;es assumidas pelos Passageiros ou pelos Motoristas entre si;</li>
<li>b) O aplicativo BIBI MOTOTAXI n&atilde;o poder&aacute; ser responsabilizado pela perda, avaria ou esquecimento de objetos no interior do ve&iacute;culo.</li>
</ol>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o se responsabilizar&aacute; por erros ocasionados pelo Passageiro em raz&atilde;o da n&atilde;o confer&ecirc;ncia do valor da corrida apresentado no Aplicativo e aprova&ccedil;&atilde;o do pagamento de referido valor, sendo o Passageiro o &uacute;nico respons&aacute;vel por este processo.</p>
<p>DA INTERRUP&Ccedil;&Atilde;O E INCONSIST&Ecirc;NCIA NO APLICATIVO BIBI MOTOTAXI:</p>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o prev&ecirc; que estar&aacute; dispon&iacute;vel ininterruptamente, que estar&aacute; sempre livre de erros, n&atilde;o podendo, por conseguinte, ser responsabilizado por danos causados aos PASSAGEIROS em virtude de qualquer interrup&ccedil;&atilde;o no funcionamento do Aplicativo BIBI MOTOTAXI.</p>
<p>O Passageiro concorda tamb&eacute;m que o Aplicativo BIBI MOTOTAXI n&atilde;o responder&aacute; por quaisquer danos ou preju&iacute;zos causados a seu aparelho celular ou qualquer outro equipamento eletr&ocirc;nico, como resultado do uso do Aplicativo BIBI MOTOTAXI.</p>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o ser&aacute; respons&aacute;vel por erros ou inconsist&ecirc;ncias no fornecimento de informa&ccedil;&otilde;es por outros sistemas independentes, especializados na presta&ccedil;&atilde;o de servi&ccedil;os de localiza&ccedil;&atilde;o no sistema de geoposicionamento global (GPS).</p>
<p>DAS INDENIZA&Ccedil;&Otilde;ES POR DANOS:</p>
<p>O Passageiro concorda em indenizar e/ou isentar o Aplicativo BIBI MOTOTAXI e seus representantes em caso de quaisquer reclama&ccedil;&otilde;es, processos, perdas, responsabilidades, danos e despesas, incluindo honor&aacute;rios advocat&iacute;cios razo&aacute;veis e custas judiciais resultantes dos danos que causar ao Aplicativo BIBI MOTOTAXI.</p>
<p>O Aplicativo BIBI MOTOTAXI ir&aacute; fornecer o valor da corrida quando o Passageiro inserir o local de origem e destino.</p>
<p>OBRIGA&Ccedil;&Otilde;ES, RESPONSABILIDADES E RISCOS DO PASSAGEIRO</p>
<p>O Passageiro atesta que utiliza os servi&ccedil;os do Aplicativo BIBI MOTOTAXI por sua livre escolha e reconhece e aceita todos os Termos.</p>
<p>DA ACEITA&Ccedil;&Atilde;O E RECUSA DOS SERVI&Ccedil;OS:</p>
<p>A aceita&ccedil;&atilde;o e a recusa da chamada efetuada por meio do Aplicativo BIBI MOTOTAXI poder&aacute; ocorrer em um primeiro momento pelo Motorista, que poder&aacute; aceitar ou negar o servi&ccedil;o quando receber a notifica&ccedil;&atilde;o do chamado.</p>
<p>O Passageiro, por sua vez, poder&aacute; cancelar por qualquer motivo a contrata&ccedil;&atilde;o. O Motorista e o Passageiro reconhecem que o Aplicativo BIBI MOTOTAXI n&atilde;o poder&aacute; ser responsabilizado por qualquer atraso, cancelamento, falha no cancelamento da contrata&ccedil;&atilde;o e falha de comunica&ccedil;&atilde;o entre Passageiro e Motorista, tampouco por qualquer atraso ou falha do Motorista na presta&ccedil;&atilde;o dos servi&ccedil;os.</p>
<p>O cancelamento reiterado de corridas pelo Passageiro poder&aacute; resultar no bloqueio tempor&aacute;rio e/ou exclus&atilde;o do Passageiro do Aplicativo, a exclusivo crit&eacute;rio do Aplicativo BIBI MOTOTAXI.</p>
<p>O Passageiro ao aceitar os produtos e/ou promo&ccedil;&otilde;es ofertadas pelo Aplicativo BIBI MOTOTAXI est&aacute; ciente de que, tamb&eacute;m, estar&aacute; sujeito aos termos e san&ccedil;&otilde;es espec&iacute;ficos, estabelecidos para os respectivos produtos e/ou promo&ccedil;&otilde;es.</p>
<p>O Passageiro reconhece e declara que compreende e tem consci&ecirc;ncia de todos os riscos envolvidos na utiliza&ccedil;&atilde;o do Aplicativo e na contrata&ccedil;&atilde;o dos servi&ccedil;os, se comprometendo a tomar os cuidados razoavelmente esperados de algu&eacute;m que escolhe um carro para transport&aacute;-lo.</p>
<p>O Passageiro reconhece e concorda que o Aplicativo BIBI MOTOTAXI realiza uma verifica&ccedil;&atilde;o pr&eacute;via dos Motoristas cadastrados em sua base de dados por meio da an&aacute;lise de sua documenta&ccedil;&atilde;o referente &agrave; regularidade do Motorista. Ap&oacute;s o recebimento da documenta&ccedil;&atilde;o de regularidade, e aprovado na fase de verifica&ccedil;&atilde;o de seguran&ccedil;a basta que o Motorista efetue o seu cadastramento no Aplicativo para participar.</p>
<p>O aplicativo BIBI MOTOTAXI n&atilde;o ser&aacute; respons&aacute;vel pelo reembolso de valores a Passageiros em virtude de quaisquer erros decorrentes de falha do Motorista, falha do passageiro ao conferir os valores e/ou quaisquer outros eventos que n&atilde;o sejam de exclusiva responsabilidade do Aplicativo BIBI MOTOTAXI nos pagamentos efetuados por meio do Aplicativo.</p>
<p>O Passageiro &eacute; o &uacute;nico respons&aacute;vel por conferir os valores a serem pagos por cada corrida por meio do Aplicativo.</p>
<p>Apesar de tomar todas as medidas necess&aacute;rias para a conveni&ecirc;ncia dos Passageiros, o Aplicativo BIBI MOTOTAXI n&atilde;o se responsabiliza por ocorr&ecirc;ncias relativas &agrave; rela&ccedil;&atilde;o estabelecida entre Motorista e Passageiro ou decorrentes do transporte efetuado.</p>
<p>DOS DESCONTOS/VOUCHERS</p>
<p>O Aplicativo BIBI MOTOTAXI, eventualmente, poder&aacute;, a seu livre e exclusivo crit&eacute;rio, oferecer descontos a todos os PASSAGEIROS, por&eacute;m os PASSAGEIROS est&atilde;o cientes que os vouchers:</p>
<p>Poder&atilde;o ser limitados at&eacute; determinado n&uacute;mero de Passageiros que os utilizarem ou a um per&iacute;odo espec&iacute;fico;</p>
<p>N&atilde;o ser&atilde;o reembolsados em dinheiro e/ou n&atilde;o ter&atilde;o direito a outro voucher caso (a) o Passageiro exceda o limite do n&uacute;mero de disponibiliza&ccedil;&atilde;o de vouchers; (b) exista algum problema entre Passageiro e Motorista no momento do pagamento; (c) ocorram quaisquer problemas sist&ecirc;micos e/ou com a operadora de cart&atilde;o; e</p>
<p>ter&atilde;o regras definidas em regulamentos espec&iacute;ficos.</p>
<p>DA AVALIA&Ccedil;&Atilde;O DO SERVI&Ccedil;O E SAN&Ccedil;&Otilde;ES</p>
<p>&Eacute; facultado aos Passageiros avaliar os Motorista que os transportaram, atribuindo notas ou tecendo coment&aacute;rios sobre os servi&ccedil;os prestados. As avalia&ccedil;&otilde;es ser&atilde;o de uso exclusivo do Aplicativo BIBI MOTOTAXI, a fim de atender cada vez melhor o Passageiro, podendo, inclusive, bloquear o Motorista em caso de reclama&ccedil;&otilde;es recorrentes.</p>
<p>O Aplicativo BIBI MOTOTAXI reserva o direito de usar as avalia&ccedil;&otilde;es para melhorar o servi&ccedil;o, seja de uso interno ou externo.</p>
<p>Em caso de qualquer ato il&iacute;cito ou criminoso, ass&eacute;dio, ou qualquer outro ato ou omiss&atilde;o que possa causar dano ao Passageiro, o Aplicativo BIBI MOTOTAXI dever&aacute; ser comunicado imediatamente sobre o ocorrido para que possa tomar as medidas que considerar necess&aacute;rias. Em hip&oacute;tese alguma o Aplicativo BIBI MOTOTAXI poder&aacute; divulgar informa&ccedil;&otilde;es pessoais de seus Passageiros em virtude de solicita&ccedil;&atilde;o do passageiro que alegar ter sido lesado por outro Passageiro, exceto mediante apresenta&ccedil;&atilde;o da correspondente solicita&ccedil;&atilde;o pela autoridade legal competente no uso de suas atribui&ccedil;&otilde;es. Orientamos, portanto, que o Passageiro lesado informe o ocorrido para as autoridades competentes para que estas tomem as medidas necess&aacute;rias para resolu&ccedil;&atilde;o do problema.</p>
<p>O Aplicativo BIBI MOTOTAXI poder&aacute; notificar, suspender ou cancelar, tempor&aacute;ria ou definitivamente, a conta de um Passageiro, a qualquer tempo, e tomar as medidas legais cab&iacute;veis, inclusive encaminhar os dados pertinentes &agrave; autoridade competente para que esta tome as medidas legais cab&iacute;veis, caso: (1) constate a viola&ccedil;&atilde;o de quaisquer das declara&ccedil;&otilde;es, garantias e obriga&ccedil;&otilde;es que constam deste Termo ou de quaisquer pol&iacute;ticas e regras adjacentes a ele; (2) suspeite que estejam sendo praticados atos fraudulentos ou dolosos; ou (3) suspeite que as atividades e atitudes tenham causado ou possam vir a causar algum dano a terceiros ou ao pr&oacute;prio Aplicativo BIBI MOTOTAXI, a seu exclusivo crit&eacute;rio.</p>
<p>O Passageiro n&atilde;o far&aacute; jus a qualquer indeniza&ccedil;&atilde;o ou compensa&ccedil;&atilde;o pelo cancelamento ou suspens&atilde;o de sua conta no Aplicativo.</p>
<p>As mesmas disposi&ccedil;&otilde;es aplicar-se-&atilde;o para os produtos e/ou promo&ccedil;&otilde;es lan&ccedil;ados pelo Aplicativo BIBI MOTOTAXI e aceitos pelo Passageiro, salvo disposi&ccedil;&atilde;o espec&iacute;fica em contr&aacute;rio nos regramentos pr&oacute;prios de cada produto e/ou promo&ccedil;&atilde;o.</p>
<p>POL&Iacute;TICA DE PRIVACIDADE</p>
<p>Possu&iacute;mos uma pol&iacute;tica expressa sobre Privacidade Online, estando todas as informa&ccedil;&otilde;es dos passageiros protegidas por nosso sistema de seguran&ccedil;a online inviol&aacute;vel. As Informa&ccedil;&otilde;es de Cadastro e algumas outras informa&ccedil;&otilde;es sobre o Passageiro est&atilde;o sujeitas ao tratamento definidos na referida pol&iacute;tica.</p>
<p>DAS FRAUDES E CHARGEBACK</p>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o se responsabilizar&aacute; por quaisquer fraudes ou CHARGEBACKS (contesta&ccedil;&otilde;es) realizadas por um PASSAGEIRO.</p>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o possui qualquer inger&ecirc;ncia sobre os CHARGEBACKS efetuados pelos Passageiros.</p>
<p>O Aplicativo BIBI MOTOTAXI n&atilde;o se responsabilizar&aacute; e n&atilde;o efetuar&aacute; o pagamento de valores referentes a CHARGEBACKS, sendo de inteira responsabilidade do Passageiro a correta utiliza&ccedil;&atilde;o do Aplicativo.</p>
<p>A utiliza&ccedil;&atilde;o do Aplicativo BIBI MOTOTAXI com o intuito de fraude, tanto por um Passageiro, quanto por um MOTORISTA, resultar&aacute; na obriga&ccedil;&atilde;o de indenizar o APLICATIVO BIBI MOTOTAXI em raz&atilde;o dos danos causados e ser&aacute; pun&iacute;vel nos termos da legisla&ccedil;&atilde;o em vigor.</p>
<p>Em todos os casos de CHARGEBACK, o APLICATIVO BIBI MOTOTAXI empenhar&aacute; seus melhores esfor&ccedil;os para resolu&ccedil;&atilde;o do problema.</p>
<p>DA LICEN&Ccedil;A DO USO DO APLICATIVO BIBI MOTOTAXI</p>
<p>Aplicativo BIBI MOTOTAXI concede ao Passageiro uma licen&ccedil;a de uso limitada, pessoal, n&atilde;o exclusiva, n&atilde;o transfer&iacute;vel, n&atilde;o comercial e plenamente revog&aacute;vel, para usar o Aplicativo em seu celular em conformidade com as condi&ccedil;&otilde;es previstas neste Termo. O Aplicativo BIBI MOTOTAXI reserva-se todos os direitos ao Aplicativo n&atilde;o expressamente concedidos neste Termo.</p>
<p>Ao utilizar o APLICATIVO ora licenciado de acordo com os termos e condi&ccedil;&otilde;es deste TERMO, o PASSAGEIRO concorda com as regras de seu funcionamento e todas as suas funcionalidades.</p>
<p>CONDI&Ccedil;&Otilde;ES GERAIS</p>
<p>Este Termo n&atilde;o gera nenhum contrato de sociedade, de mandato, franquia ou rela&ccedil;&atilde;o de trabalho entre o Aplicativo BIBI MOTOTAXI e o Passageiro.</p>
<p>Este Termo pode ser modificado pelo Aplicativo BIBI MOTOTAXI a qualquer momento, de forma unilateral. As modifica&ccedil;&otilde;es entrar&atilde;o em vigor automaticamente na data da publica&ccedil;&atilde;o da nova vers&atilde;o no Aplicativo e/ou no SITE do Aplicativo BIBI MOTOTAXI, devendo ficar dispon&iacute;vel a todos os PASSAGEIROS.</p>
<p>Este ser&aacute; regido e interpretado de acordo com as leis da Rep&uacute;blica Federativa do Brasil.</p>
<p>Ao cadastrar-se como Passageiro no Aplicativo e aceitar eletronicamente o presente Termo, por meio do clique no bot&atilde;o &ldquo;aceito os termos de uso&rdquo;, o Passageiro declara automaticamente e incondicionalmente estar de acordo com este Termo e todas as demais pol&iacute;ticas e regras disponibilizadas no Aplicativo BIBI MOTOTAXI.</p>
<p>Caso qualquer cl&aacute;usula, termo ou disposi&ccedil;&atilde;o deste Termo, seja declarada nula, tal nulidade n&atilde;o afetar&aacute; quaisquer outras cl&aacute;usulas, termos ou disposi&ccedil;&otilde;es aqui contidas, as quais permanecer&atilde;o em pleno vigor e efeito. A toler&acirc;ncia por qualquer uma das Partes com rela&ccedil;&atilde;o a qualquer viola&ccedil;&atilde;o do presente Termo ou sua omiss&atilde;o no exerc&iacute;cio de qualquer direito outorgado pelo mesmo, n&atilde;o ser&aacute; considerado como nova&ccedil;&atilde;o ou ren&uacute;ncia em rela&ccedil;&atilde;o a qualquer viola&ccedil;&atilde;o futura, seja semelhante ou n&atilde;o, ou ao exerc&iacute;cio por qualquer uma das partes de qualquer direito futuro conferido por este termo.</p>
    </div>
  );
}

export default Termo;
